

#define PLACEHOLDERFLAG MAINDIR\placeholder\bdsm_AfA_Placeholder_Flag_##MODSUFFIX##_co.paa

#define PLACEHOLDERINSIGNIA MAINDIR\placeholder\bdsm_AfA_Placeholder_Insignia_##MODSUFFIX##_ca.paa

#define PLACEHOLDERMARKER MAINDIR\placeholder\bdsm_AfA_Placeholder_Marker_##MODSUFFIX##_co.paa

#define PLACEHOLDERUI MAINDIR\placeholder\bdsm_AfA_Placeholder_Icon_##MODSUFFIX##_ca.paa

#define PLACEHOLDERLOGO MAINDIR\placeholder\bdsm_AfA_Placeholder_Logo_##MODSUFFIX##.paa


	#define Q_PLACEHOLDERFLAG QUOTE(PLACEHOLDERFLAG)

	#define Q_PLACEHOLDERINSIGNIA QUOTE(PLACEHOLDERINSIGNIA)

	#define Q_PLACEHOLDERMARKER QUOTE(PLACEHOLDERMARKER)

	#define Q_PLACEHOLDERUI QUOTE(PLACEHOLDERUI)

	#define Q_PLACEHOLDERLOGO QUOTE(PLACEHOLDERLOGO)


	#define PLACEHOLDERUILINE picture = Q_PLACEHOLDERUI ;

	#define PLACEHOLDERINSIGNIALINE texture = Q_INSIGNIALINE ;
