:: Name:     create_Submod_folder_structure.bat
:: Purpose:  creates the folder structure used by each Submod, in adherence with the format used in the Additions_for_Antistasi mod.
:: Author:   Giddi
:: Revision: 08.April.2020

@echo off
REM.-- Prepare the Command Processor --
SETLOCAL ENABLEEXTENSIONS
SETLOCAL ENABLEDELAYEDEXPANSION

Rem Gets user input for the necessary Folder name and the Modsuffix that will be used.
Rem Variable "MODFOLDVAR" is the Foldername.
Rem Variable "MODSUFFIXVAR" is the Modsuffix.
SET /P MODFOLDVAR=please enter the Modfolder name:
SET /P MODSUFFIXVAR=please enter the Modsuffix, used for every asset:

Rem Creates the basic folders with the previously inputed Foldername
MD "%~dp0..\Addons\%MODFOLDVAR%\includes"
MD "%~dp0..\Addons\%MODFOLDVAR%\macros"
Rem -----------------------------------------
MD "%~dp0..\Addons\%MODFOLDVAR%\misc\flags"
MD "%~dp0..\Addons\%MODFOLDVAR%\misc\insignia"
MD "%~dp0..\Addons\%MODFOLDVAR%\misc\logo"
MD "%~dp0..\Addons\%MODFOLDVAR%\misc\marker"
Rem -----------------------------------------
MD "%~dp0..\Addons\%MODFOLDVAR%\objects"
MD "%~dp0..\Addons\%MODFOLDVAR%\placeholder"

Rem creates the macro definition file, that will be included at the beginning of the config.cpp.
echo #define MODFOLDER %MODFOLDVAR% > "%~dp0..\Addons\%MODFOLDVAR%\Submod_name_macros.hpp"
echo #define MODSUFFIX %MODSUFFIXVAR% >> "%~dp0..\Addons\%MODFOLDVAR%\Submod_name_macros.hpp"


Rem creates a basic config.cpp with all the standard include calls.
echo #define _ARMA_ >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo. >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo #include "Submod_name_macros.hpp" >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo. >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo #include "\AfA\Addons\main\global_macros\basic_macros.hpp" >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo. >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo //▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀▄▀// >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo. >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo class CfgPatches >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo { >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo 	class MODFOLDER >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo 	{ >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo 		units[] = {}; >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo 		weapons[] ={}; >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo 		requiredVersion = 0.1; >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo 		requiredAddons[] = {"rhsusf_main","A3_Characters_F","A3_Data_f","A3_Weapons_F","A3_Characters_F_Proxies"}; >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo 	}; >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"
echo }; >> "%~dp0..\Addons\%MODFOLDVAR%\config.cpp"

Rem creates basic model.config
echo class CfgSkeletons >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo { >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	class Default >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	{ >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		isDiscrete = 1; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		skeletonInherit = ""; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		skeletonBones[] = {}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	class OFP2_ManSkeleton >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	{ >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		isDiscrete = 0; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		skeletonInherit = ""; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		skeletonBones[] = >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		{ >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Pelvis","", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Spine","Pelvis", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Spine1","Spine", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Spine2","Spine1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Spine3","Spine2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Camera","Pelvis", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"weapon","Spine1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"launcher","Spine1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo. 			 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			// Head skeleton in hierarchy >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"neck","Spine3", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"neck1","neck", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"head","neck1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo. 			 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			// New facial features >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_Hub","head", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_Jawbone","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_Jowl","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_chopRight","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_chopLeft","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_LipLowerMiddle","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_LipLowerLeft","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_LipLowerRight","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_Chin","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_Tongue","Face_Jawbone", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CornerRight","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CheekSideRight","Face_CornerRight", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CornerLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CheekSideLeft","Face_CornerLeft", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CheekFrontRight","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CheekFrontLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CheekUpperRight","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_CheekUpperLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_LipUpperMiddle","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_LipUpperRight","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_LipUpperLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_NostrilRight","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_NostrilLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_Forehead","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_BrowFrontRight","Face_Forehead", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_BrowFrontLeft","Face_Forehead", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_BrowMiddle","Face_Forehead", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_BrowSideRight","Face_Forehead", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_BrowSideLeft","Face_Forehead", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_Eyelids","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_EyelidUpperRight","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_EyelidUpperLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_EyelidLowerRight","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"Face_EyelidLowerLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"EyeLeft","Face_Hub", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"EyeRight","Face_Hub",			 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo.			 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			// Left upper side >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftShoulder","Spine3", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftArm","LeftShoulder", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftArmRoll","LeftArm", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftForeArm","LeftArmRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftForeArmRoll","LeftForeArm", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHand","LeftForeArmRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandRing","LeftHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandRing1","LeftHandRing", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandRing2","LeftHandRing1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandRing3","LeftHandRing2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandPinky1","LeftHandRing", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandPinky2","LeftHandPinky1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandPinky3","LeftHandPinky2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandMiddle1","LeftHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandMiddle2","LeftHandMiddle1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandMiddle3","LeftHandMiddle2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandIndex1","LeftHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandIndex2","LeftHandIndex1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandIndex3","LeftHandIndex2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandThumb1","LeftHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandThumb2","LeftHandThumb1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftHandThumb3","LeftHandThumb2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo.			 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			// Right upper side >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightShoulder","Spine3", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightArm","RightShoulder", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightArmRoll","RightArm", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightForeArm","RightArmRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightForeArmRoll","RightForeArm", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHand","RightForeArmRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandRing","RightHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandRing1","RightHandRing", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandRing2","RightHandRing1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandRing3","RightHandRing2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandPinky1","RightHandRing", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandPinky2","RightHandPinky1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandPinky3","RightHandPinky2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandMiddle1","RightHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandMiddle2","RightHandMiddle1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandMiddle3","RightHandMiddle2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandIndex1","RightHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandIndex2","RightHandIndex1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandIndex3","RightHandIndex2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandThumb1","RightHand", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandThumb2","RightHandThumb1", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightHandThumb3","RightHandThumb2", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo. 			 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			// Left lower side >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftUpLeg","Pelvis", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftUpLegRoll","LeftUpLeg", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftLeg","LeftUpLegRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftLegRoll","LeftLeg", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftFoot","LeftLegRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"LeftToeBase","LeftFoot", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo.			 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			// Right lower side >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightUpLeg","Pelvis", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightUpLegRoll","RightUpLeg", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightLeg","RightUpLegRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightLegRoll","RightLeg", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightFoot","RightLegRoll", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"RightToeBase","RightFoot" >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		// location of pivot points (local axes) for hierarchical animation >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		pivotsModel="A3\anims_f\data\skeleton\SkeletonPivots.p3d"; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo }; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo.  >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo class CfgModels >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo { >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	class Default >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	{ >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		sectionsInherit=""; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		sections[] = {}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		skeletonName = ""; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo.  >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	class ArmaMan: Default >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	{ >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		htMin = 60;          // Minimum half-cooling time (in seconds) >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		htMax = 1800;        // Maximum half-cooling time (in seconds) >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		afMax = 30;          // Maximum temperature in case the model is alive (in celsius) >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		mfMax = 0;           // Maximum temperature when the model is moving (in celsius) >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		mFact = 1;           // Metabolism factor - number from interval <0, 1> (0 - metabolism has no influence, 1 - metabolism has full influence (no other temperature source will be considered)). >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		tBody = 37;  // Metabolism temperature of the model (in celsius) >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo. >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		sections[] = >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		{ >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"osobnost","Head_Injury","Body_Injury","l_leg_injury","l_arm_injury","r_arm_injury","r_leg_injury", "injury_body", "injury_legs", "injury_hands", >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 			"clan","clan_sign","Camo","CamoB","Camo1","Camo2","personality","hl", "injury_head", "insignia" >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 		skeletonName = "OFP2_ManSkeleton"; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo 	}; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo. 		 >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"
echo }; >> "%~dp0..\Addons\%MODFOLDVAR%\Model.cfg"

Rem Copies the Asset folder creator Batch file to the Submod base folder.
COPY NOT_USE_FROM_HERE_create_object_folders.bat "%~dp0..\Addons\%MODFOLDVAR%\create_object_folder_and_files.bat"
echo done
PAUSE
